### ISSUE TITLE
Private key for encryption?

### ISSUE THREAD

**Issue by gR0OT** [serengil/LightPHE#17]
IMO those two lines In LightPHE.__init__().encrypt() should check for public key, since you can encrypt with only public key, but you need private key for decryption.
```python
119: if self.cs.keys.get("private_key") is None:
120:    raise ValueError("You must have private key to perform encryption")
```

Proposed fix:
```python
119: if self.cs.keys.get("public_key") is None:
120:    raise ValueError("You must have public key to perform encryption")
```

**Comment by serengil** [comment]
Good point!

**Comment by gR0OT** [comment]
Also I found that when performing `export_keys()` in lightphe.\_\_init\_\_ in case of exporting (publishing) the public key, it deletes private key in the process. This leaves the LightPHE object (who should have private key, because it generated it) unable to decrypt.
```python
246: if public is True and keys.get("private_key") is not None:
247:     del keys["private_key"]
```

My current workaround:
```python
gm = LightPHE('Paillier')
gm.export_keys('private.key', public=False)
gm.export_keys('public.key', public=True)
gm = LightPHE('Paillier', key_file='private.key')
```

Proposed fix:
Don't delete the `private_key` from `keys` when performing `export_keys()`, just export the `public_key`
```python
pubkey = {'public_key': keys['public_key']}
with open(target_file, "w", encoding="UTF-8") as file:
    file.write(pubkey)
```

@serengil should i create new issue for that?

**Comment by serengil** [comment]
@gR0OT yes please

i will fix them all tonight - i hope

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/LightPHE/pull/19

**Comment by serengil** [comment]
Also, release is published in pip

https://pypi.org/project/lightphe/0.0.6/
