### ISSUE TITLE
Public key export deletes private key

### ISSUE THREAD

**Issue by gR0OT** [serengil/LightPHE#18]
When performing export_keys() in lightphe.__init__ in case of exporting (publishing) the public key, it deletes private key in the process. This leaves the LightPHE object (who should have private key, because it generated it) unable to decrypt.
```python
246: if public is True and keys.get("private_key") is not None:
247:     del keys["private_key"]
```
Current workaround:
```python
gm = LightPHE('Paillier')
gm.export_keys('private.key', public=False)
gm.export_keys('public.key', public=True)
gm = LightPHE('Paillier', key_file='private.key')
```
Proposed fix:
Don't delete the private_key from keys when performing export_keys(), just export the public_key
```python
pubkey = {'public_key': keys['public_key']}
with open(target_file, "w", encoding="UTF-8") as file:
    file.write(pubkey)
```

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/LightPHE/pull/19
