### ISSUE TITLE
Paillier not working with scalar non-integer float

### ISSUE THREAD

**Issue by kostrom** [serengil/LightPHE#21]
If someone tries to work with float values in paillier, it doesn't work, but it works for integers. If it only supports integers, you may want to raise an exception, in keeping with how you handle some other illegal operations.

see https://stackoverflow.com/questions/78335087/the-sum-does-not-get-decrypted

**Comment by serengil** [comment]
Float numbers are not invalid actually. They are converted to integers for that module.

```python
cs = LightPHE(algorithm_name = "Paillier")

m1 = 17
c1 = cs.encrypt(m1)

# increasing something 5%
k = 1.05

# scalar multiplication - private key is not required!
c4 = k * c1

# proof of work
assert cs.decrypt(c4) == k * m1
```

Besides, if you set your plaintext as tensor, then you are able to restore that float number.

```python
cs = LightPHE(algorithm_name = "Paillier")

m = [1.5]
c = cs.encrypt(m)
p = cs.decrypt(c)
assert p[0] == 1.5
```

**Comment by kostrom** [comment]
`from lightphe import LightPHE
cs = LightPHE(algorithm_name="Paillier")
def validate(m):
    return m == cs.decrypt(cs.encrypt(m))
assert validate(1)
assert validate([1.5])
assert validate(1.0)
assert validate(1.5) # does not work for scalar float
`
Thanks for the workaround. I notice that the working vector of float creates a Fraction object, but the scalar float goes into parse_int and breaks it down to a fraction form, but returns a Ciphertext object.

**Comment by serengil** [comment]
They are all working for me. Are you using latest version?

**Comment by kostrom** [comment]
pip says this is version 0.0.6

**Comment by kostrom** [comment]
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32

from lightphe import LightPHE
cs = LightPHE(algorithm_name="Paillier")

m = 0.5
c = cs.encrypt(m)
print (c)
print (c.value)
print (cs.decrypt(c))

The result is a different large integer each time. One example:
Ciphertext(4922236528608796958846746588856423007916048798962477533781817619365633697325781550310212188324426679830638156638168677716104162861723368950471576089968798265186067536585262890999551828526603098457138708105316241290356667810727996717063041280990292421509852573848746382971495371575884363892331801459088266056263296822284217735228810846513811562773585729263266463491832609884275528416373445393310448315775555480589931990786433374114491875143152201524542983831458022888057533769829260893420154296328186405682975065490419261182064893854706074644935068680571429787260863682691199488370523205802299040717157400554985373)
4922236528608796958846746588856423007916048798962477533781817619365633697325781550310212188324426679830638156638168677716104162861723368950471576089968798265186067536585262890999551828526603098457138708105316241290356667810727996717063041280990292421509852573848746382971495371575884363892331801459088266056263296822284217735228810846513811562773585729263266463491832609884275528416373445393310448315775555480589931990786433374114491875143152201524542983831458022888057533769829260893420154296328186405682975065490419261182064893854706074644935068680571429787260863682691199488370523205802299040717157400554985373
3160776990604745647081572122326825228093787522500982730374347988572421971214894550600891079327673062817591884978456486978621806738130920750356955734498673096320017239353437210121462431193272851721939264910466572918152023133068103002383357016447565929890091709586032192185552280463164426557306804290606846899

**Comment by kostrom** [comment]
Actually, looking at the source, I might be able to submit an MR, but if you're not reproducing the issue ... that might be counterproductive.

**Comment by serengil** [comment]
Yes please

**Comment by kostrom** [comment]
My quick fix of handling float like [float] broke a few other things. Fraction doesn't have value, and why can't we multiply a Fraction by a constant?

**Comment by serengil** [comment]
@kostrom you may consider to make your python version same with me

**Comment by serengil** [comment]
Closed due to inactivity
