### ISSUE TITLE
Incorrect Decryption result for sum of encrypted values with mixed signs

### ISSUE THREAD

**Issue by zakharova-anastasiia** [serengil/LightPHE#26]
**Description**:
I encountered an issue when using the library (version 0.0.8) for partially homomorphic encryption in Python 3.11.9. Specifically, when I try to decrypt the sum of two encrypted values, where one is negative, the result is incorrect. The expected output and the actual output differ significantly.

**Environment**:
- **Library Version**: 0.0.8
- **Python Version**: 3.11.9

**Cryptosystem Configuration**:
```python
from lightphe import LightPHE
cs = LightPHE(algorithm_name = "Paillier")
```
The cryptosystem is built with the default parameters using the Paillier algorithm.

**Steps to Reproduce**:
Here is a code snippet that reproduces the issue:
```python
a = 1.5 * cs.encrypt([1.5])
b = 2.5 * cs.encrypt([-2.5])

cs.decrypt(a + b)[0] # Output: 8.713756943261783e+301 (Expected: -4.0)
cs.decrypt(a)[0] + cs.decrypt(b)[0] # Outputs: -4.0
```

The issue is reproducible only if one of the values is negative. For example, the following code works as expected:
```python
a = 1.5 * cs.encrypt([1.5])
b = 2.5 * cs.encrypt([2.5])

cs.decrypt(a + b)[0] # Outputs: 8.5
cs.decrypt(a)[0] + cs.decrypt(b)[0] # Outputs: 8.5
```

**Observed Behavior**:
When summing encrypted values where one is negative, the decryption of the sum yields an extremely large integer, which is obviously incorrect:
```plaintext
8.713756943261783e+301
```

**Expected Behavior**:
The result of `cs.decrypt(a + b)` should be the same as the sum of `cs.decrypt(a)` and `cs.decrypt(b)`, which should be:
```plaintext
-4.0
```

**Additional Information**:
I found the following comment in the source code, which may be related to the issue:
```python
# if one is positive and one is negative, then i cannot know
# the result is positive or negative. trust mod calculations.
```

This seems to indicate a potential problem when summing encrypted values with mixed signs.

**Request**:
Could you please investigate this issue?

**Comment by serengil** [comment]
Actually that is not bug. When you sum a positive and negative number, we cannot know the result is positive or negative. So, it shows result for that mod. Unfortunately, no solution for this in PHE.
